# Generated by Django 4.0.2 on 2022-02-26 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gate', '0003_remove_historicalgate_history_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(db_index=True, max_length=100, verbose_name='Color')),
                ('plate_nimber', models.CharField(db_index=True, max_length=100, verbose_name='Plate number')),
                ('model', models.CharField(blank=True, max_length=25, null=True, verbose_name='Model')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('visitor_img', models.CharField(max_length=256, verbose_name='Visitor IMG')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'IN'), (2, 'OUT')], default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.car')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.gate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('job_title', models.CharField(max_length=256, verbose_name='Staff Name')),
                ('reason_of_visit', models.CharField(max_length=256, verbose_name='Reason Of Visit')),
                ('national_id', models.CharField(max_length=256, verbose_name='National ID')),
                ('visitor_img', models.CharField(max_length=256, verbose_name='Visitor IMG')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Staff Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_operation', models.BooleanField(default=False, verbose_name='Operation')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Supervisor')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.gate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saff',
                'ordering': ['-created_at'],
                'permissions': [('can_add_saff', 'can add saff'), ('can_update_saff', 'can update saff'), ('can_delete_saff', 'can delete saff')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.visitor'),
        ),
    ]
