# Generated by Django 4.0.2 on 2022-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_visitor_user_visitor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='plate_nimber',
            new_name='plate_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='visitor_img',
        ),
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(default=1, upload_to='Cars/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_img',
            field=models.ImageField(blank=True, null=True, upload_to='visitor/% Y/% m/% d/'),
        ),
    ]
