# Generated by Django 4.0.2 on 2022-02-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_alter_camera_description_alter_camera_name_and_more'),
        ('staff', '0003_rename_plate_nimber_car_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at'], 'verbose_name': 'saff'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gate.gate'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='job_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='national_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reason_of_visit',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Reason Of Visit'),
        ),
    ]
