# Generated by Django 4.0.2 on 2022-03-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0006_alter_gate_description_alter_gate_name'),
        ('staff', '0004_alter_staff_options_remove_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gate',
        ),
        migrations.AddField(
            model_name='staff',
            name='gate',
            field=models.ManyToManyField(blank=True, null=True, to='gate.Gate'),
        ),
    ]
