# Generated by Django 4.0.2 on 2022-03-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0006_staff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(max_length=256, verbose_name='Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APIKey',
                'ordering': ['-created_at'],
            },
        ),
    ]
