# Generated by Django 4.0.2 on 2022-03-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0009_remove_camera_extra_data_remove_gate_extra_data_and_more'),
        ('staff', '0008_apikey_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='car',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='visitortrace',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='staff',
            name='gate',
            field=models.ManyToManyField(to='gate.Gate'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='national_id',
            field=models.CharField(default='2424324323424', max_length=256, verbose_name='National ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('name', 'national_id')},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='extra_data',
        ),
    ]
