# Generated by Django 4.0.2 on 2022-03-10 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0009_remove_apikey_extra_data_remove_car_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('tabs', models.JSONField(verbose_name='tabs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
