# Generated by Django 4.0.2 on 2022-03-10 23:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0010_tabs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabs',
            new_name='Tab',
        ),
    ]
