# Generated by Django 4.0.2 on 2022-03-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_tabs_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tabs',
            field=models.JSONField(default='{}', verbose_name='tabs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
