# Generated by Django 4.0.2 on 2022-03-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staff_tabs_delete_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tabs',
            field=models.JSONField(blank=True, null=True, verbose_name='tabs'),
        ),
    ]
