# Generated by Django 4.0.2 on 2022-03-18 15:54

from django.db import migrations, models
import staff.models.car


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_staff_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_img',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to=staff.models.car.upload_to, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
