# Generated by Django 4.0.2 on 2022-03-18 16:25

from django.db import migrations, models
import staff.models.visitor


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_car_car_img_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_img',
        ),
        migrations.AddField(
            model_name='visitor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.visitor.upload_to),
        ),
    ]
