# Generated by Django 4.0.2 on 2022-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_visitor_visitor_img_visitor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Plate number'),
        ),
    ]
