# Generated by Django 4.0.2 on 2022-02-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name Of Camera')),
                ('url', models.URLField(verbose_name='Camer Url')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Camera')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
                'permissions': [('can_add_camera', 'can add camera'), ('can_update_camera', 'can update camera'), ('can_delete_camera', 'can delete camera')],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name Of Gate')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Camera')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name Of Gate')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Camera')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCamera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When This Object Created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When This Object Updated')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name Of Camera')),
                ('url', models.URLField(verbose_name='Camer Url')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Camera')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Camera',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
