# Generated by Django 4.0.2 on 2022-02-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='gate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gate.gate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='gate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gate.gate'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Gate'),
        ),
        migrations.AlterField(
            model_name='historicalgate',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description Of Gate'),
        ),
    ]
