# Generated by Django 4.0.2 on 2022-02-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_camera_gate_historicalcamera_gate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgate',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCamera',
        ),
        migrations.DeleteModel(
            name='HistoricalGate',
        ),
    ]
