# Generated by Django 4.0.2 on 2022-02-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_remove_historicalgate_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-created_at'], 'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
    ]
