# Generated by Django 4.0.2 on 2022-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_alter_camera_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URl'),
        ),
    ]
