# Generated by Django 4.0.2 on 2022-03-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_alter_camera_description_alter_camera_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Name'),
        ),
    ]
