# Generated by Django 4.0.2 on 2022-03-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0006_alter_gate_description_alter_gate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
