# Generated by Django 4.0.2 on 2022-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_alter_gate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='description',
            field=models.CharField(default='123', max_length=256, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
