# Generated by Django 4.0.2 on 2022-03-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0008_alter_gate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
